name: Visual Regression Test

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize ]
  push:
    branches: [ main ]

jobs:
  golden_test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Get Flutter version from .tool-versions
        id: get-version
        run: echo "FLUTTER_VERSION=$(grep flutter .tool-versions | awk '{print $2}' | sed 's/-stable//')" >> $GITHUB_ENV
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      - name: Run Golden Tests
        run: flutter test --tags=golden

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install modules
        run: npm ci

      - name: Run reg-suit
        run: npx reg-suit run
        env:
          REGSUIT_CLIENT_ID: ${{ secrets.REGSUIT_CLIENT_ID }}